---
- name: Instalando - LAMP - AWX
  hosts: all
  tasks:
  - name: Garantindo Pacotes - Like Debian-
    apt: 
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items:
    - apache2
    - mysql-server
    - php7
    when: ansible_os_family == "Debian"

  - name: Garantindo Pacotes - Like Fedora
    dnf: 
      name: "{{ item }}"
      state: present
    with_items:
    - httpd
    - mariadb
    - php
    when: ansible_distribution == "Fedora"

  - name: Garantindo Pacotes - Like Fedora
    yum: 
      name: "{{ item }}"
      state: present
    with_items:
    - httpd
    - mariadb
    - php
    when: ansible_distribution == "CentOS"
