---
- name: Instalando - LAMP - AWX
  hosts: all
  tasks:
  - name: Garantindo Pacotes - Like Debian-
    apt: 
      name: ['apache2','mysql-server','php7']
      state: present
      update_cache: true
    when: ansible_os_family == "Debian"

  - name: Garantindo Pacotes - Like Fedora
    dnf: 
      name: ['httpd','mariadb','php']
      state: present
    when: ansible_distribution == "Fedora"

  - name: Garantindo Pacotes - Like CentOS
    yum: 
      name: ['httpd','maridb','php']
      state: present
    when: ansible_distribution == "CentOS"
