---
- name: Instalando - LAMP - AWX
  hosts: all
  tasks:
  - name: Garantindo Pacotes - Like Debian-
    apt: 
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items:
    - apache2
    - mysql-server
    - php7
    when: ansible_os_family == "Debian"

  - name: Garantindo Pacotes - Like RedHat
    yum: 
      name: {{item}}
      state: present
    with_items:
    - httpd
    - mariadb
    - php7
    when: ansible_os_family == "RedHat"
